sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master
env:
  matrix:
  - INSTANCE=smoke-ubuntu-1604
  - INSTANCE=smoke-ubuntu-1704

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: 
  - chef exec rspec
# kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec rspec
